version: '3.3'
services:
  db:
    image: postgres
    env_file: '.env'
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: /bin/sh -c "rm -f /usr/src/app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "${PORT}:${PORT}"
    env_file: '.env'
    depends_on:
      - db
    volumes:
      - "~/.bash_history:/root/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"