version: '3.3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: app
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./services/app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db